const store = [
  {
    workoutId: 1,
    workoutDate: new Date('2020/7/28'),
    numSetsPer: 3,
    numExercises: 2,
    notes: 'asdas as asdasas asd agfdshds df dsf hsdfh sd fhsd fhhdfs dfhsdfh',
    workoutTime: '4:18PM',
    workoutTitle: 'Strength',
    userId: 24,
    exercise1: 'deadlifts',
    set1_1Weight: '135',
    set1_1reps: '8',
    set1_2Weight: '235',
    set1_2reps: '6',
    set1_3Weight: '335',
    set1_3reps: '5',
    exercise2: 'deadlifts',
    set2_Weight: '135',
    set2_1reps: '8',
    set2_2Weight: '235',
    set2_2reps: '6',
    set2_3Weight: '335',
    set2_3reps: '5',
  },
  {
    workoutId: 2,
    workoutDate: new Date('2020/7/27'),
    numSetsPer: 3,
    numExercises: 2,
    notes: 'asdas as asdasas asd agfdshds df dsf hsdfh sd fhsd fhhdfs dfhsdfh',
    workoutTime: '9:38AM',
    workoutTitle: 'Calisthenics',
    userId: 12,
    exercise1: 'handstand pushups',
    set1_1Weight: 'body',
    set1_1reps: '8',
    set1_2Weight: 'body',
    set1_2reps: '6',
    set1_3Weight: 'body',
    set1_3reps: '5',
    exercise2: 'pistol squats',
    set2_Weight: 'body',
    set2_1reps: '8',
    set2_2Weight: 'body',
    set2_2reps: '6',
    set2_3Weight: 'body',
    set2_3reps: '5',
  }
];


export default {
  store
}